export const POLICY_RULE_ORDER = [
  "INPUT_IDENTITY_INTEGRITY",
  "PAYMENT_STATE_CONFLICT",
  "ORIGINAL_PAYMENT_SATISFIED",
  "SAFETY_DEPENDENCY_AVAILABLE",
  "INTENT_MONEY_INTEGRITY",
  "PAYMENT_LINK_LIMIT",
  "CUSTOMER_CONTACT_LIMIT",
  "RECOVERY_WINDOW_LIMIT",
  "AI_RECOMMENDATION_BOUNDARY",
  "EXPECTED_VALUE_POSITIVE",
  "DIAGNOSIS_ACTION_COMPATIBILITY",
  "POLICY_APPROVED",
] as const;

export type PolicyRuleId = (typeof POLICY_RULE_ORDER)[number];

export const PROACTIVE_RECOVERY_ACTIONS = [
  "WAIT_FOR_RECOVERY",
  "SEND_PAYMENT_LINK",
  "REQUEST_METHOD_CHANGE",
] as const;

export const CUSTOMER_CONTACT_ACTIONS = [
  "SEND_PAYMENT_LINK",
  "REQUEST_METHOD_CHANGE",
] as const;
